### ISSUE TITLE
[cob_moveit_bringup] setup_assistant does not support xacro --inorder

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_manipulation#105]
thus, we cannot use the `cob_moveit_bringup/setup_assistant.launch` file anymore...
needs to be added to https://github.com/ros-planning/moveit_setup_assistant/blob/kinetic-devel/src/setup_assistant_main.cpp#L57 similar as it is done for https://github.com/ros-planning/moveit_setup_assistant/blob/kinetic-devel/src/collisions_updater.cpp#L130

@ipa-bfb FYI

**Comment by mathias-luedtke** [comment]
Just use the jade version. The indigo xacro with `--inorder` is just using the jade version under the hood.
This way you don't  need to specify the `--inorder ` flag to use the other new features.

**Comment by fmessmer** [comment]
well, `sudo apt-get ros-jade-xacro` is easy, but how would you then handle your indigo workspace to use jade xacro? if you `source /opt/ros/jade/setup.bash` you have to re-configure your workspace everytime...

**Comment by mathias-luedtke** [comment]
Hmm, the conditional blocks do not work without inorder processing.
But we can use already processed URDFs for now and switch to kinetic sooner than later ;)

**Comment by fmessmer** [comment]
If I find a slot, I might propose a (consistency) fix for setup_assistant...should not be too much work...and still Indigo is LTS so they might merge it...

**Comment by mathias-luedtke** [comment]
Indigo and jade have been excluded intentionally: https://github.com/ros-planning/moveit/pull/238

**Comment by gavanderhoorn** [comment]
Not sure if you also care about the gui, but see ros-planning/moveit#540.

I might have to revisit that PR and add support for the command line side as well.

**Comment by fmessmer** [comment]
With https://github.com/ros-planning/moveit/pull/540 merged, it is now possible to create **new** moveit config packages for xacro's using Jade+ features...
However, moveit_setup_assistant still fails to load xacro's using Jade+ features when editing an existing moveit_config package (see https://github.com/ros-planning/moveit/issues/511#issuecomment-338576884)

**Comment by gavanderhoorn** [comment]
Should be as simple as adding `use_jade_xacro: true` to the `.setup_assistant` of an existing config. See https://github.com/ros-industrial/fanuc/blob/61a84f2684136053824b34406220fa2eaf4b7ad9/fanuc_lrmate200ic5h_moveit_config/.setup_assistant#L5 fi.

**Comment by fmessmer** [comment]
@gavanderhoorn 
thanks for pointing this out
