### ISSUE TITLE
kinetic support needed

### ISSUE THREAD

**Issue by benmaidel** [ipa320/cob_manipulation#99]

**Comment by fmessmer** [comment]
see https://github.com/ipa320/cob_manipulation/pull/100/commits/f16b9d36bd4239af28fdb9afc45ce1e27a3ff3c2

but discussion is about removing `cob_kinematics` anyway #72

**Comment by mathias-luedtke** [comment]
> kinetic support needed

This is about the FCL compatibility issues.

**Comment by fmessmer** [comment]
- ~~cob_kinematics~~ (moveit_kinematics?) --> https://github.com/ipa320/cob_manipulation/pull/100#issuecomment-280855916
 - ~~cob_pick_place_action~~ (shape_tools, c++11, MoveGroup deprecation warning)
 - ~~cob_collision_monitor~~ (c++11)
 - ~~cob_obstacle_distance_moveit~~ (c++11, boost::shared_ptr vs. std::shared_ptr)

**Comment by mathias-luedtke** [comment]
@ipa-bnm: do you have a list?

**Comment by benmaidel** [comment]
> @ipa-bnm: do you have a list?

nope, unfortunately not.

**Comment by fmessmer** [comment]
my [list](https://github.com/ipa320/cob_manipulation/issues/99#issuecomment-280369518) is complete and compile issues already solved in #101
